name: Run UI tests

workflow dispatch:
  branches: [ main ]

jobs:
  build:
    run-on: ubuntu-latest

    steps:
      - name: Start selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 3
          browsers: chrome
          last-versions: 1

      - name: checkout
        uses: actions/checkout@v2

      - name: run selenide tests
        run:
          mvn clean test -pl :selenide-tests -e -DsuiteXmlFile=src/test/resources/xmls/debug.xml


