name: Run UI selenoid tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
            version: 1.10.1
            args: -limit 3
            browsers: chrome
            last-versions: 1

      - name: Setup java 17
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '17'
            cache: 'maven'
            run: java --version

      - name: Checkout project with tests
        uses: actions/checkout@v4

      - name: run selenide tests
        run:
           mvn clean test -pl :selenide-tests -e -DsuiteXmlFile=src/test/resources/xmls/debug.xml


