name: Run UI selenoid tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
            version: 1.10.1
            args: -limit 3
            browsers: chrome
            last-versions: 1
      - name: Checkout project with tests
        uses: actions/checkout@v4

      - name: Setup java 17
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '17'

      - name: run selenide tests
        run: |
            ./mvnw clean install
            ./mvnw clean test -pl :selenide-tests -e -DsuiteXmlFile=src/test/resources/xmls/debug.xml

      - name: install allure
        run: |
            sudo apt-get install default-jre
            wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure_2.18.1-1_all.deb
            sudo dpkg -i allure_2.18.1-1_all.deb
            allure --version

      - name: allure-generate
        working-directory: ./selenide-tests/target/
        run: allure generate

      - name: attach-report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report-artifact
          path: selenide-tests/target
          retention-days: 5
